/**
 * api.js
 * Reads pre-fetched results from data/results.json (generated by GitHub Actions).
 * This avoids CORS issues – no browser-side API calls needed.
 */

/**
 * Builds a lookup: "HomeSwedish_AwaySwedish" → { result, goals }
 * by matching against the groupMatches from results.json
 * (which are keyed by English team name pairs).
 *
 * @param {Array}  matchList   - ordered list of Swedish match labels from tips.json
 * @param {Object} teamNames   - { "Mexiko": "Mexico", ... }
 * @param {Object} groupMatches - { "Mexico_South Africa": { result, goals } }
 */
function buildMatchResultsMap(matchList, teamNames, groupMatches) {
  // Build reverse lookup: English → Swedish
  const enToSv = {};
  for (const [sv, en] of Object.entries(teamNames)) {
    enToSv[en] = sv;
    // Also try common short names the API might return
    enToSv[en.toLowerCase()] = sv;
  }

  // Parse a Swedish match label to get home/away team names
  function parseLabel(label) {
    const m = label.match(/[\d.]+ \w+, [\d.]+\s+(.+?)\s*-\s*(.+?)\s*\(([A-L])\)/);
    return m ? { home: m[1].trim(), away: m[2].trim() } : null;
  }

  const results = {};

  for (const label of matchList) {
    const parsed = parseLabel(label);
    if (!parsed) continue;

    const homeEN = teamNames[parsed.home];
    const awayEN = teamNames[parsed.away];
    if (!homeEN || !awayEN) continue;

    // Try both home_away and away_home (API might order differently)
    const key1 = `${homeEN}_${awayEN}`;
    const key2 = `${awayEN}_${homeEN}`;
    const found = groupMatches[key1] ?? groupMatches[key2];
    if (found) {
      // If teams were swapped, flip the result
      if (groupMatches[key2] && !groupMatches[key1]) {
        results[label] = { result: found.result === '1' ? '2' : found.result === '2' ? '1' : 'X', goals: found.goals };
      } else {
        results[label] = found;
      }
    }
  }

  return results;
}

/**
 * Load the pre-generated results file.
 * Returns { matchResults, roundTeams, goalscorers }
 */
export async function loadResults(matchList, teamNames) {
  const res = await fetch(`./data/results.json?t=${Date.now()}`);
  if (!res.ok) throw new Error(`Could not load results.json: ${res.status}`);
  const data = await res.json();

  const matchResults = buildMatchResultsMap(matchList, teamNames, data.groupMatches ?? {});

  return {
    matchResults,
    roundTeams: data.roundTeams ?? { sexton: [], atton: [], kvarts: [], semi: [], final: [], winner: '', thirdPlace: '' },
    goalscorers: data.goalscorers ?? {},
    liveMatches: data.liveMatches ?? [],
    updatedAt: data.updatedAt,
  };
}

